import {
  BookOpen,
  CalendarDays,
  CandlestickChart,
  Gauge,
  Home,
  Landmark,
  ListChecks,
  NotebookPen,
  Search,
  Settings,
  ShieldCheck,
  TestTube2,
  WalletCards,
} from "lucide-react";

export const navItems = [
  { to: "/dashboard", key: "nav.dashboard", icon: Home },
  { to: "/my-portfolio", key: "nav.myPortfolio", icon: WalletCards },
  { to: "/markets", key: "nav.markets", icon: CandlestickChart },
  { to: "/instruments/MSFT", key: "nav.instruments", icon: Search },
  { to: "/screener", key: "nav.screener", icon: Gauge },
  { to: "/simulated-portfolio", key: "nav.simulatedPortfolio", icon: TestTube2 },
  { to: "/dividends", key: "nav.dividends", icon: CalendarDays },
  { to: "/tax-advisor", key: "nav.taxAdvisor", icon: Landmark },
  { to: "/data-quality", key: "nav.dataQuality", icon: ShieldCheck },
  { to: "/watchlists", key: "nav.watchlists", icon: ListChecks },
  { to: "/journal", key: "nav.journal", icon: NotebookPen },
  { to: "/guides", key: "nav.guides", icon: BookOpen },
  { to: "/settings", key: "nav.settings", icon: Settings },
];
