import {
  Bell,
  BookOpen,
  Bot,
  CalendarDays,
  CandlestickChart,
  Gauge,
  GraduationCap,
  Home,
  Landmark,
  LineChart,
  ListChecks,
  Newspaper,
  NotebookPen,
  PieChart,
  Radar,
  Search,
  Settings,
  ShieldCheck,
  TestTube2,
  WalletCards,
} from "lucide-react";

export const navItems = [
  { to: "/dashboard", key: "nav.dashboard", icon: Home },
  { to: "/markets", key: "nav.markets", icon: CandlestickChart },
  { to: "/instruments/MSFT", key: "nav.instruments", icon: Search },
  { to: "/insights", key: "nav.insights", icon: Radar },
  { to: "/alerts", key: "nav.alerts", icon: Bell },
  { to: "/news", key: "nav.news", icon: Newspaper },
  { to: "/my-portfolio", key: "nav.myPortfolio", icon: WalletCards },
  { to: "/simulated-portfolio", key: "nav.simulatedPortfolio", icon: TestTube2 },
  { to: "/dividend-fisher", key: "nav.dividendFisher", icon: CalendarDays },
  { to: "/tax-advisor", key: "nav.taxAdvisor", icon: Landmark },
  { to: "/forecasting", key: "nav.forecasting", icon: LineChart },
  { to: "/data-quality", key: "nav.dataQuality", icon: ShieldCheck },
  { to: "/screener", key: "nav.screener", icon: Gauge },
  { to: "/watchlists", key: "nav.watchlists", icon: ListChecks },
  { to: "/journal", key: "nav.journal", icon: NotebookPen },
  { to: "/playbooks", key: "nav.playbooks", icon: BookOpen },
  { to: "/learn", key: "nav.learn", icon: GraduationCap },
  { to: "/demo", key: "nav.demo", icon: PieChart },
  { to: "/copilot", key: "nav.copilot", icon: Bot },
  { to: "/settings", key: "nav.settings", icon: Settings },
];
