from __future__ import annotations

from typing import Protocol


class MarketDataProvider(Protocol):
    def search_instruments(self, query: str) -> list[dict[str, object]]: ...
    def get_daily_prices(self, ticker: str) -> list[dict[str, object]]: ...
    def get_dividends(self, ticker: str) -> list[dict[str, object]]: ...
    def get_company_profile(self, ticker: str) -> dict[str, object] | None: ...
